Add Kafka Client integration for publish messages for payment updater UC
pagopa/io-functions-messages-cqrs pull request #11
Opened 2022-06-24 18:13 UTC by AleDore

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2022-07-06 14:01 UTC, michaeldisaro requested changes

2022-07-06 14:01 UTC, michaeldisaro commented on CosmosApiMessagesChangeFeed/__tests__/handler.test.ts
> +      "",
ditto

2022-07-07 09:15 UTC, AleDore commented on package.json
> +    "@chasdevs/avro-to-typescript": "^1.4.0",
We have already used in io-functions-elt

2022-07-07 09:48 UTC, AleDore commented on utils/storable_error.ts
> +      queueClient.sendMessage(
Yes, because we are sending only metadata with payment attributes here

2022-07-07 09:54 UTC, AleDore commented on CosmosApiMessagesChangeFeed/handler.ts
> +      pipe(
ditto

2022-07-07 16:53 UTC, fabriziopapi commented on HandleMessageChangeFeedPublishFailures/handler.ts
> +        enrichMessageContent(messageModel, blobService, retrievedMessage),
Ok, I see that for costruction pending message should never go down this queue.

2022-07-07 20:34 UTC, gquadrati requested changes

2022-07-07 20:34 UTC, gquadrati commented on CosmosApiMessagesChangeFeed/function.json
> +      "startFromBeginning": true
Do we need to replay all messages?

2022-07-12 08:40 UTC, fabriziopapi approved these changes

2022-07-12 15:40 UTC, gquadrati approved these changes
LGTM

2022-07-28 16:06 UTC, merged